// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukzgdkanmfzybxhexbtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVremdka2FubWZ6eWJ4aGV4YnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTc5MjksImV4cCI6MjA2OTAzMzkyOX0.tU6g-IP8J5cDiCcZj9FmS6ZvV0k-NZc-8gXE5Jxa_cY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});